import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('artifacts/browser',{recursive:true});
const browser=await chromium.launch();
try {
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.MWBridge);
 await page.getByRole('button',{name:'Settings and account'}).click();
 const settings=page.getByRole('dialog',{name:'Settings'});
 assert(await settings.getByRole('button',{name:/Sign in with Google/}).isVisible());
 await page.keyboard.press('Escape');await settings.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Filters',exact:true}).click();
 const filters=page.getByRole('dialog',{name:'Filter cards'});
 await filters.getByRole('checkbox',{name:'Red',exact:true}).check();
 assert.equal(await page.evaluate(()=>F.colors.size),0);
 await filters.getByRole('button',{name:'Apply filters'}).click();
 assert(await page.evaluate(()=>F.colors.has('red')));
 await page.getByRole('button',{name:/^Filters/}).click();
 await filters.getByRole('checkbox',{name:'Blue',exact:true}).check();
 await page.keyboard.press('Escape');
 assert.equal(await page.evaluate(()=>F.colors.has('blue')),false);
 await page.getByRole('button',{name:/^Filters/}).click();
 assert(await filters.getByText('Version',{exact:true}).isVisible());
 assert.equal(await filters.getByRole('checkbox',{name:'Parallel',exact:true}).count(),1);
 await filters.locator('summary').filter({hasText:'Set'}).click();
 assert(await filters.getByText('Booster packs',{exact:true}).isVisible());
 assert.equal(await filters.getByRole('checkbox',{name:'Official catalog'}).count(),0);
 await filters.getByRole('button',{name:'Reset',exact:true}).click();
 await filters.getByRole('button',{name:'Apply filters'}).click();
 assert.equal(await page.evaluate(()=>filterTokens(F).length),0);
 const iconCentered=selector=>page.locator(selector).first().evaluate(button=>{const b=button.getBoundingClientRect(),s=button.querySelector('svg').getBoundingClientRect();return Math.abs((b.left+b.right-s.left-s.right)/2)<1&&Math.abs((b.top+b.bottom-s.top-s.bottom)/2)<1;});
 assert(await iconCentered('.addbtn'));
 // Desktop puts the tabs in the top bar; phones keep a bottom tab bar (checked again at 390px below).
 assert(await page.locator('nav.tabbar').evaluate(el=>el.getBoundingClientRect().top<innerHeight/4));
 await page.evaluate(async()=>{await window.MWBridge.importList({kind:'collection',title:'Browser test collection',items:[{id:CATALOG[0].id,quantity:3,pricePaid:10}]});});
 await page.locator('#colBody .item-main').first().click();
 await page.locator('[data-quantity]').waitFor();
 assert.equal(await page.locator('[data-quantity]').inputValue(),'3');
 assert.match(await page.locator('#colSummary').innerText(),/3\s+cards owned/i);
 await page.getByRole('button',{name:'One more'}).click();
 await page.waitForFunction(()=>/4\s+cards owned/i.test(document.querySelector('#colSummary')?.innerText||''));
 await page.reload();await page.locator('#tabCollection').click();await page.locator('#colBody .item-main').first().click();await page.locator('[data-quantity]').waitFor();
 assert.equal(await page.locator('[data-quantity]').inputValue(),'4');
 await page.keyboard.press('Escape');
 await page.screenshot({path:'artifacts/browser/desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/browser/mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert(await page.locator('nav.tabbar').evaluate(el=>el.getBoundingClientRect().top>innerHeight/2));
 await page.getByRole('button',{name:'Collection actions'}).click();
 await page.getByRole('menuitem',{name:'Price history'}).click();
 await page.getByText('No dates have observed prices for every card in this collection yet. Missing prices are never counted as zero.').waitFor();
 const chart=await browser.newPage();
 await chart.route('**/app-config.js*',r=>r.fulfill({contentType:'text/javascript',body:"window.MW_CONFIG={apiUrl:'https://api.example.test',supabaseUrl:'https://project.supabase.co',supabasePublishableKey:'sb_publishable_test',googleAuthEnabled:true}"}));
 await chart.route('https://api.example.test/**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(r.request().url().endsWith('price-history')?{a:[['2026-09-16',100],['2026-09-17',120]]}:[])}));
 await chart.goto('http://127.0.0.1:8000');await chart.waitForFunction(()=>window.MWCloud);
 await chart.waitForFunction(()=>window.MWCloud.signInAvailable);
 assert.equal(await chart.getByRole('dialog',{name:'Account & sharing'}).count(),0);
 assert.equal(await chart.getByRole('textbox',{name:'Email address'}).count(),0);
 await chart.evaluate(async()=>{const el=document.createElement('div');el.id='chartTest';document.body.append(el);await window.MWCloud.showHistory(el,[{id:'a',quantity:2}]);});
 assert.match(await chart.locator('#chartTest').innerText(),/\+¥40/);
 assert.equal(await chart.locator('#chartTest svg circle').count(),2);
 await chart.route('https://project.supabase.co/auth/v1/authorize**',r=>r.fulfill({contentType:'text/html',body:'OAuth test redirect'}));
 await chart.getByRole('button',{name:'Settings and account'}).click();
 await chart.getByRole('dialog',{name:'Settings'}).getByRole('button',{name:/Sign in with Google/}).click();
 await chart.waitForURL(/\/auth\/v1\/authorize/);
 const oauthUrl=new URL(chart.url());
 assert.equal(oauthUrl.searchParams.get('provider'),'google');
 assert.equal(oauthUrl.searchParams.get('redirect_to'),'http://127.0.0.1:8000/');
 await chart.close();
 const profile=await browser.newPage({viewport:{width:390,height:844}});profile.on('pageerror',e=>errors.push(e.message));
 const mockSession={access_token:'test-token',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user:{id:'11111111-1111-4111-8111-111111111111',email:'collector@example.com',app_metadata:{provider:'google'},user_metadata:{}}};
 await profile.addInitScript(s=>localStorage.setItem('sb-gvrmtovkdlabsqmipaaw-auth-token',JSON.stringify(s)),mockSession);
 await profile.route('**/v1/me/lists',r=>r.fulfill({contentType:'application/json',body:JSON.stringify([{id:'sample',localId:'sample',kind:'collection',title:'My collection',items:[{id:'OP01-001'}],revision:2,shared:true}])}));
 await profile.goto('http://127.0.0.1:8000');
 await profile.waitForFunction(()=>window.MWCloud?.account?.());
 await profile.getByRole('button',{name:'Settings and account'}).click();
 await profile.getByRole('dialog',{name:'Settings'}).getByRole('button',{name:/collector@example\.com/}).click();
 const account=profile.getByRole('dialog',{name:'Account & sharing'});
 await account.getByText('My collection').waitFor();
 assert(await account.getByRole('button',{name:'Close account panel'}).isVisible());
 assert(await account.locator('.cloud-close').evaluate(button=>{const b=button.getBoundingClientRect(),s=button.querySelector('svg').getBoundingClientRect();return Math.abs((b.left+b.right-s.left-s.right)/2)<1&&Math.abs((b.top+b.bottom-s.top-s.bottom)/2)<1;}));
 assert(await account.getByRole('button',{name:'Save current list'}).isVisible());
 await account.getByRole('button',{name:'Close account panel'}).click();
 await account.waitFor({state:'hidden'});
 await profile.locator('#tabWishlist').click();
 await profile.locator('.title-btn').click();
 await profile.getByRole('menuitem',{name:'Manage lists…'}).click();
 const listDialog=profile.getByRole('dialog',{name:'Your wishlists'});
 assert(await listDialog.getByRole('button',{name:'Close Your wishlists'}).isVisible());
 await profile.keyboard.press('Escape');
 await listDialog.waitFor({state:'hidden'});
 assert(await profile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await profile.close();
 assert.deepEqual(errors,[]);console.log('Browser checks passed: settings + account, dialog controls, filters, collection editor quantities, persistence, list switcher, mobile layout, no JS errors.');
} finally {await browser.close();}
