import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('artifacts/browser',{recursive:true});
const browser=await chromium.launch();
try {
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>window.MWBridge);
 await page.getByRole('button',{name:'Account',exact:true}).click();
 await page.getByRole('dialog',{name:'Account & sharing'}).waitFor();
 assert.match(await page.getByRole('dialog',{name:'Account & sharing'}).innerText(),/Send sign-in link/);
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Advanced',exact:true}).click();
 assert(await page.getByRole('button',{name:/^Variant/}).isVisible());
 await page.getByRole('button',{name:'Fewer filters',exact:true}).click();
 await page.evaluate(async()=>{await window.MWBridge.importList({kind:'collection',title:'Browser test collection',items:[{id:CATALOG[0].id,quantity:3,pricePaid:10}]});});
 await page.locator('[data-quantity]').waitFor();
 assert.equal(await page.locator('[data-quantity]').inputValue(),'3');
 assert.match(await page.locator('#colSummary').innerText(),/3\s+cards owned/i);
 await page.locator('[data-quantity]').fill('4');await page.locator('[data-quantity]').dispatchEvent('change');
 await page.waitForFunction(()=>document.querySelector('#colSummary')?.innerText.toLowerCase().includes('4\ncards owned'));
 await page.reload();await page.locator('#tabCollection').click();await page.locator('[data-quantity]').waitFor();
 assert.equal(await page.locator('[data-quantity]').inputValue(),'4');
 await page.screenshot({path:'artifacts/browser/desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/browser/mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Price history',exact:true}).click();
 await page.getByText('No dates have observed prices for every card in this collection yet. Missing prices are never counted as zero.').waitFor();
 const chart=await browser.newPage();
 await chart.route('**/app-config.js',r=>r.fulfill({contentType:'text/javascript',body:"window.MW_CONFIG={apiUrl:'https://api.example.test',supabaseUrl:'https://project.supabase.co',supabasePublishableKey:'sb_publishable_test',googleAuthEnabled:true}"}));
 await chart.route('https://api.example.test/**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(r.request().url().endsWith('price-history')?{a:[['2026-09-16',100],['2026-09-17',120]]}:[])}));
 await chart.goto('http://127.0.0.1:8000');await chart.waitForFunction(()=>window.MWCloud);
 let otpPayload;
 await chart.route('https://project.supabase.co/auth/v1/otp**',async r=>{if(r.request().method()==='POST')otpPayload=r.request().postDataJSON();await r.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*'},body:'{}'});});
 await chart.getByRole('button',{name:'Account',exact:true}).click();
 assert(await chart.getByRole('button',{name:'Continue with Google'}).isVisible());
 assert(await chart.getByRole('button',{name:'Send sign-in link'}).isVisible());
 assert(await chart.getByRole('textbox',{name:'Email address'}).isVisible());
 await chart.getByRole('textbox',{name:'Email address'}).fill('existing@example.test');
 await chart.getByRole('button',{name:'Send sign-in link'}).click();
 await chart.getByRole('status').getByText('Check your email for the sign-in link.').waitFor();
 assert.equal(otpPayload.create_user,false);
 await chart.getByRole('button',{name:'Close',exact:true}).click();
 await chart.evaluate(async()=>{const el=document.createElement('div');el.id='chartTest';document.body.append(el);await window.MWCloud.showHistory(el,[{id:'a',quantity:2}]);});
 assert.match(await chart.locator('#chartTest').innerText(),/\+¥40/);
 assert.equal(await chart.locator('#chartTest svg circle').count(),2);
 await chart.route('https://project.supabase.co/auth/v1/authorize**',r=>r.fulfill({contentType:'text/html',body:'OAuth test redirect'}));
 await chart.getByRole('button',{name:'Account',exact:true}).click();
 await chart.getByRole('button',{name:'Continue with Google'}).click();
 await chart.waitForURL(/\/auth\/v1\/authorize/);
 const oauthUrl=new URL(chart.url());
 assert.equal(oauthUrl.searchParams.get('provider'),'google');
 assert.equal(oauthUrl.searchParams.get('redirect_to'),'http://127.0.0.1:8000/');
 await chart.close();
 assert.deepEqual(errors,[]);console.log('Browser checks passed: account state, filters, collection quantities, persistence, mobile layout, no JS errors.');
} finally {await browser.close();}
